package br.gov.ce.fortaleza.sepog.domain;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class IssueChamadoKSPessoa implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public IssueChamadoKSPessoa() {
    }




}